#SingleInstance, Force
#NoEnv
SendMode Input
#Persistent	
SetBatchLines, -1
SendMode, Event
SetKeyDelay 25, 10

IfExist, C:\INTPHARM\Idle.txt   ;Idle.txt only exists if it's already run
    {
    ExitApp
    }

FileReadLine, DispxSiteCode, C:\INTPHARM\DISPX\sitecode.txt, 1

;FileAppend, SITECODE: %DispxSiteCode% `n, C:\INTPHARM\Idle.txt

FileAppend,`t`t`t`t7MMF'-------------7MM---7MM---------------------`t`t`t`tSITECODE: %DispxSiteCode%`n, C:\INTPHARM\Idle.txt
FileAppend,`t`t`t`t--MM------------------MM-----MM---------------------`n, C:\INTPHARM\Idle.txt
FileAppend,`t`t`t`t--MM-----.dMM"bMM-----MM------.gP""Ya--`n, C:\INTPHARM\Idle.txt
FileAppend,`t`t`t`t--MM---.AP---------MM-----MM----.M'---------Yb`n, C:\INTPHARM\Idle.txt
FileAppend,`t`t`t`t--MM---8MI---------MM-----MM----8M"""""""`n, C:\INTPHARM\Idle.txt
FileAppend,`t`t`t`t--MM----Mb---------MM-----MM----YM.----------.`n, C:\INTPHARM\Idle.txt
FileAppend,`t`t`t`t.JMML.--Wbmd"MML..JMML.---Mbmmd'--`n, C:\INTPHARM\Idle.txt



FileAppend,`nThis report is generated by reviewing known issues and offering a potential fix as a result.`nThe fix offered may not always be accurate but simply offers a best guess as to the cause.`nPlease confirm the problem is resolved before disconnecting.`n`nVersion 1.0.2`t`t`t`t`t`t`t`t`t%A_space%%A_space%%A_space%%A_space%%A_space%%A_space%%A_space%%A_space%%A_space%%A_space%%A_space%%A_space%Written by Aaron Beecham`n############################################################################################`n`n, C:\INTPHARM\Idle.txt

;======================CHECK FOR REQUIRED TEXT FILES======================

    IniRead, DISPSYS, C:\INTPHARM\DISPX\dispx.ini, Settings, Dispense

    if RegExMatch(DISPSYS, "ZED") 
        {
            IfNotExist, C:\INTPHARM\DISPX\zed.txt
            {
            InputBox, ZEDapss , ZED DISPENSE APSS, Enter the APSS directory.`nAdd directory to dataset.dbf manually., , 250, 150, , , ,
            FileAppend, %ZEDapss%,  C:\INTPHARM\DISPX\zed.txt
            }
        }


    pFile := "C:\INTPHARM\POSX\REF\settings.dbf"
        Loop, %pFile%
        {
        FileRead, pIn, %A_LoopFileLongPath%
        if RegExMatch(pIn, "ZED") 
            {
                IfNotExist, C:\INTPHARM\POSX\PRG\zedstart.txt
                {
                InputBox, ZEDdate , ZED START DATE, ZED start date., , 250, 150, , , ,
                FileAppend, %ZEDdate%,  C:\INTPHARM\POSX\PRG\zedstart.txt
                }
            }
        }

;====================================================================

IfNotExist, C:\INTPHARM\CRON\
    {
    FileAppend, `n> WARNING < The CRON directory does not exist. Please update DISPX/CRON so that CRON exists in its own folder`, rather than `ninside the DISPX directory.`n, C:\INTPHARM\Idle.txt
    }

IfNotExist, C:\Users\All Users\Start Menu\Programs\StartUp\hsnet.lnk
    {
    FileCreateShortcut, C:\INTPHARM\HSNET\hsnet.exe, C:\INTPHARM\hsnet.lnk ;C:\Users\All Users\Start Menu\Programs\StartUp\hsnet.lnk
    ;FileCopy, C:\INTPHARM\hsnet.lnk, C:\Users\All Users\Start Menu\Programs\StartUp\hsnet.lnk
    FileAppend, `n> The HSNET shortcut is missing from the Startup folder. A copy of the hsnet.lnk shortcut file has been created in the C:\INTPHARM directory.`nYou will need to copy it to C:\Users\All Users\Start Menu\Programs\StartUp\ manually.`n, C:\INTPHARM\Idle.txt
    }

        IfNotExist, C:\INTPHARM\HSNET\hsnet.exe
            {
            FileAppend, `n> The HSNET Executable is missing. Add exceptions and copy the EXE back to the store computer.`nYou can find standalone copies of the EXE's at G:\Support\Site Essentials\INTELLIPHARM SOFTWARE\`n, C:\INTPHARM\Idle.txt
            } 

IfExist, C:\INTPHARM\POSX
    {
        
        FormatTime, Date,, yyyyMMdd
        FileReadLine, SCODE, C:\INTPHARM\POSX\PRG\sitecode.txt, 1

        SCODE = %SCODE% ;easy way to trim the spaces at the end of sitecodes text files

        IfNotExist, C:\INTPHARM\POSX\REF\%SCODE%_PXLOG_%Date%.txt
            {
            FileAppend, `n> No POSX log file was created for todays date.`nThe computer was likely turned off and our software was not run.`n, C:\INTPHARM\Idle.txt
            }  

        IfNotExist, C:\INTPHARM\POSX\PRG\posx.exe
            {
            FileAppend, `n> The POSX Executable is missing. Add exceptions and copy the EXE back to the store computer.`nYou can find standalone copies of the EXE's at G:\Support\Site Essentials\INTELLIPHARM SOFTWARE\`n, C:\INTPHARM\Idle.txt
            }  

        Process, Exist, posx.exe
            {
            If ErrorLevel
            FileAppend, `n> The POSX Executable is currently running. The software is potentially locked up.`nThe usual cause is an old version of the restarteverything.bat. Try updating the batch file and run again.`nIf this is a FRED install - confirm fredov3 and stopspwd text files are present and correct.`n, C:\INTPHARM\Idle.txt
            }


;======================RESTART EVERYTHING BATCH READING======================

        rebatchFile := "C:\INTPHARM\CRON\restarteverything.bat"
        Loop, %rebatchFile%
        {
        FileRead, rebIn, %A_LoopFileLongPath%
        if RegExMatch(rebIn, "net stop HSNET.EXE 2>NUL") 
            {
            FileAppend, `n> BAD RESTARTEVERYTHING.BAT`nThe restarteverything batch file is using the old method which can potentially lock up POSX.`nReplace it with the latest batch file at G:\Support\Site Essentials\INTELLIPHARM SOFTWARE\CRON\STAND ALONE CRON\CRON\`n, C:\INTPHARM\Idle.txt
            sIn = ; Memory cleared
            }
        }

;======================POSX READING======================

        FileReadLine, POSXver, C:\INTPHARM\POSX\REF\%SCODE%_PXLOG_%Date%.txt, 2 ;getting line for POSX version

        pFile := "C:\INTPHARM\POSX\REF\" SCODE "_PXLOG_" Date ".txt"
        Loop, %pFile%
        {
        FileRead, pIn, %A_LoopFileLongPath%
        if RegExMatch(pIn, "Error running:  SQL_STZED  Line:373  Error:1429") 
            {
            FileAppend, `n> Error found in latest POSX log file.`nERROR READS >>>`tError running:  SQL_STZED  Line:373  Error:1429`nSOLUTION >>>`t`tDATASET.dbf is missing Dataodbc entries. The format for dataset is 'SERVERNAME\APSS'.`n`t`t`tThe server name can be found in zed.txt file in DISPX directory. If not`, you confirm with the ODBC.`n, C:\INTPHARM\Idle.txt
            sIn = ; Memory cleared
            }
        if RegExMatch(pIn, "FredNXT store is not licensed") 
            {
            FileAppend, `n> Error found in latest POSX log file.`nERROR READS >>>`tFredNXT store is not licensed`, check POSX version`nSOLUTION:`t`tThe fnauth.zip file is missing. You need to add the username and password to the fnauth.txt and zip it up`n`t`t`twith the password f_n3xt`n, C:\INTPHARM\Idle.txt
            sIn =
            }
        if RegExMatch(pIn, "POSX is not an object") 
            {
            FileAppend, `n> Error found in latest POSX log file.`nERROR READS >>>`tPOSX is not an object`nSOLUTION:`t`tUnknown specific cause as yet. This is likely due to a corrupt file in the POSX directory.`n`t`t`tBackup the POSX directory and do a complete reinstall.`n, C:\INTPHARM\Idle.txt
            sIn =
            }
        if RegExMatch(pIn, "Compressed file missing") 
            {
            FileAppend, `n> Error found in the latest POSX log file.`nERROR READS >>>`tCompressed file missing`nSOLUTION >>>`t`tThis is almost always caused by a permissions conflict.`n`t`t`tEither use an HSNET launch.`n, C:\INTPHARM\Idle.txt
            sIn =
            }
        if RegExMatch(pIn, "Dataset file is empty - configuration required") 
            {
            FileAppend, `n> Error found in the latest POSX log file.`nERROR READS >>>`tDataset file is empty - configuration required`nSOLUTION >>>`t`tIf this is POSWORKS - Copy over the POSWORKS dataset from G drive to POSX/REF.`n, C:\INTPHARM\Idle.txt
            sIn =
            }
        if RegExMatch(pIn, "Error message:  Cannot load 32-bit DLL FCE32.DLL") 
            {
            FileAppend, `n> Error found in the latest POSX log file.`nERROR READS >>>`tError message:  Cannot load 32-bit DLL FCE32.DLL`nSOLUTION >>>`t`tAdd the files found here: G:\Support\Shared Tech Resources\TOOLS\DLL FILES\CMECOMM\ to the`n`t`t`tPOSX PRG folder.`n, C:\INTPHARM\Idle.txt
            sIn =
            }
        }

;======================DATASET READING======================

        datasetFile := "C:\INTPHARM\POSX\REF\dataset.dbf"
        Loop, %datasetFile%
        {
        FileRead, dsIn, %A_LoopFileLongPath%
        if RegExMatch(dsIn, "PURCHFILE STOPS") 
            {
            FileAppend, `n> The PURCHFILE section of the DATASET.DBF is currently set to STOPS - This should usually be set to FREDO.`nConfirm the setup for this store is STOPS - if not update to FREDO.`nThis is not relevant for FRED NEXT sites.`n, C:\INTPHARM\Idle.txt
            sIn =
            }
        }
    }

IfExist, C:\INTPHARM\DISPX\
    {
        FormatTime, Date,, yyyyMMdd

        IfNotExist, C:\INTPHARM\DISPX\LOGS\DISPX_%Date%.txt
            {
            FileAppend, `n> No DIPSX log file was created for todays date.`nThe computer was likely turned off and our software was not run.`n, C:\INTPHARM\Idle.txt
            }  
        IfNotExist, C:\INTPHARM\DISPX\dispx.exe
            {
            FileAppend, `n> The DISPX Executable is missing. Add exceptions and copy the EXE back to the store computer.`nYou can find standalone copies of the EXE's at G:\Support\Site Essentials\INTELLIPHARM SOFTWARE\`n, C:\INTPHARM\Idle.txt
            }  
        Process, Exist, dispx.exe
            {
            If ErrorLevel
            FileAppend, `n> The DISPX Executable is currently running. The software is potentially locked up.`nThe usual cause is an old version of POSX. Try updating and run again.`n, C:\INTPHARM\Idle.txt
            }

;======================DISPX READING======================

        FileReadLine, SCODE, C:\INTPHARM\DISPX\sitecode.txt, 1

        SCODE = %SCODE%

        dFile := "C:\INTPHARM\DISPX\LOGS\DISPX_" Date ".txt"
        Loop, %dFile%
        {
        FileRead, dIn, %A_LoopFileLongPath%
        if RegExMatch(dIn, "rxdata.dbf not found") 
            {
            FileAppend, `n> Error found in the latest DISPX log file.`nERROR READS >>>`trxdata.dbf not found`nSOLUTION >>>`t`tEither the file is in use or the AV is blocking it. First - check to ensure the AV is allowing MSOAP and `n`t`t`tIntellipharm software. If that’s set up`, check the MINFOS end of day time. It could be that the EOD is still`n`t`t`trunning while we are attempting to extract.`n, C:\INTPHARM\Idle.txt
            sIn =
            }
        if RegExMatch(dIn, "script.dbf not found") 
            {
            FileAppend, `n> Error found in the latest DISPX log file.`nERROR READS >>>`tscript.dbf not found`nSOLUTION >>>`t`tThe dispx.ini file needs to be updated with the new location of the script.dbf file.`n`t`t`tYou're looking for a FREADHEALTH\FRED\DBFS\script.dbf file location. Check the Fred programs' 'Help'`n`t`t`tsection for the database location. If the location is the same as the dispx.ini it likely means the server`n`t`t`tcomputer is being turned off during the extraction time.`n, C:\INTPHARM\Idle.txt
            sIn =
            }
        if RegExMatch(dIn, "Log Transfer PLAIN failed [ftperror.txt]") 
            {
            FileAppend, `n> Error found in the latest DISPX log file.`nERROR READS >>>`tLog Transfer PLAIN failed [ftperror.txt] (there are likely other similar lines)`n`nSOLUTION >>>`t`tThere is a high chance that the AV or Firewall is blocking the extracted files from being sent. Make sure there are exceptions.`n, C:\INTPHARM\Idle.txt
            sIn =
            }
        if RegExMatch(dIn, "See chillog_dsp_") 
            {
            FileAppend, `n> Error found in the latest DISPX log file.`nERROR READS >>>`tSee chillog_dsp_%SCODE%.log`nSOLUTION >>>`t`tIf this is a FRED NEXT site`, it's very likely that the cause is that the exctration is getting congested with`n`t`t`tall the other sites extracting at the same time. To fix this`, simply change the extraction time to an hour or`n`t`t`ttwo from the current extraction time.`n, C:\INTPHARM\Idle.txt
            sIn =
            }
        if RegExMatch(dIn, "See chillog_stk_") 
            {
            FileAppend, `n> Error found in the latest DISPX log file.`nERROR READS >>>`tSee chillog_stk_%SCODE%.log`nSOLUTION >>>`t`tIf this is a FRED NEXT site - this usually occurs when running on an older version of dispx.exe.`n`t`t`tTry using the latest version from G:\Support\Testing\dispx_bleeding_edge\`n, C:\INTPHARM\Idle.txt
            sIn =
            }
        if RegExMatch(dIn, "Error message:  Data type mismatch.") 
            {
            FileAppend, `n> Error found in the latest DISPX log file.`nERROR READS >>>`tError message:  Data type mismatch.`nSOLUTION >>>`t`tThis occurs when there is an entry in the Database that we are extracting from that POSX isn't expecting.`n`t`t`tIt could be something like a letter in a field that POSX thinks should be Numerals only.`n`t`t`tThe latest version of POSX should have resolved this issue.`n`t`t`tTry using the latest version from G:\Support\Testing\dispx_bleeding_edge\`n, C:\INTPHARM\Idle.txt
            sIn =
            }
        if RegExMatch(dIn, "Fail-2") 
            {
            FileAppend, `n> Error found in the latest DISPX log file.`nERROR READS >>>`tCreating chilkat95 object... "Fail-2"`nSOLUTION >>>`t`tLikely an old DISPX install. Easiest fix is to backup the current DISPX folder and do a clean DISPX install.`n`t`t`tIf you're unable to rename the DISPX folder`, it's likely a very old install with CRON still nested inside it.`n`t`t`tOpen the task manager and end the cron.exe task. You will now be able to rename the DISPX folder.`n`n`t`t`tIf the above does not work`, try this:`n`t`t`tManually register the DLL file located C:\intpharm\dispx\CHILKATAX-9.5.0-WIN32.DLL`n`t`t`tIf that does not fix it`, manually register all DLL files in the CHILKAT directory.`n, C:\INTPHARM\Idle.txt
            sIn =
            }
        if RegExMatch(dIn, "OLE IDispatch exception code") 
            {
            FileAppend, `n> Error found in the latest DISPX log file.`nERROR READS >>>`tError message:  OLE IDispatch exception code`nSOLUTION >>>`t`tThe LOTS database at this store is likely using the OLEDB variant.`n`t`t`tGo to C:\INTPHARM\POSX\PRG\ and open the lotsconn.txt.`n`t`t`tLook for the part starting with "Provider=SQLNCLI10.1" and change it to say "Provider=SQLOLEDB".`n, C:\INTPHARM\Idle.txt
            sIn =
            }
        if RegExMatch(dIn, "ERROR: Empty latest script value - no new data retrieved") 
            {
            FileAppend, `n> Error found in the latest DISPX log file.`nERROR READS >>>`tERROR: Empty latest script value - no new data retrieved`nSOLUTION >>>`t`tThis often happens on Terry White stores.`n`t`t`tTry changing the extraction time to a couple hours later.`n`t`t`tIt's also worth backing up the MSOAP folder and letting it recreate it.`n, C:\INTPHARM\Idle.txt
            sIn =
            }
        if RegExMatch(dIn, "Compressed file missing") 
            {
            FileAppend, `n> Error found in the latest DISPX log file.`nERROR READS >>>`tCompressed file missing`nSOLUTION >>>`t`tThis is almost always caused by a permissions conflict.`n`t`t`tEither use an HSNET launch.`n, C:\INTPHARM\Idle.txt
            sIn =
            }
        if RegExMatch(dIn, "Endpoint connection not alive - Webservice may not be running") 
            {
            FileAppend,`n> Error found in the latest DISPX log file.`nERROR READS >>>`tEndpoint connection not alive - Webservice may not be running`nSOLUTION >>>`t`tFirst`, check to make sure the endpoint.txt is located in the DISPX directory. If it is not there`, copy the one`n`t`t`tfrom G:\Support\Shared Tech Resources\Systems\MINFOS\`n`t`t`tIf you need to`, update the endpoint location in the endpoint.txt`, it should look like this:`n`t`t`thttp://<server_name_here>:4434/LegacyDataAccess/LegacyDataAccessService`n`t`t`tIf you have done all that and it is still not working`, you will need to contact MINFOS to have them make`n`t`t`tsure the endpoint is active.`n, C:\INTPHARM\Idle.txt
            sIn =
            }
        if RegExMatch(dIn, "No data in date range") 
            {
            FileAppend,`n> Error found in the latest DISPX log file.`nERROR READS >>>`tNo data in date range`nSOLUTION >>>`t`tLikely a DISPENSE system change.`n`t`t`tDouble check the system in use.`n, C:\INTPHARM\Idle.txt
            sIn =
            }
        if RegExMatch(dIn, "ZED dispense") 
            {
            IfNotExist, C:\INTPHARM\DISPX\zed.txt
                {
                FileAppend, `n> It appears this site has DISPX set up for ZED. However there is no zed.txt in the DISPX directory.`nMake sure you add this file as it is required for DISPX to run.`nThis file should have the server location inside it. In the format of SERVER\APSS`n, C:\INTPHARM\Idle.txt
                sIn =
                }
            }
        }

;======================MSOAP FOLDER======================

        IfExist, C:\INTPHARM\MSOAP\msoap.exe
            {
                IfNotExist, C:\INTPHARM\MSOAP\endpoint.txt
                    {
                    FileAppend, `n> No endpoint.txt in MSOAP Directory.`nNormally this file should be pulled from DISPX`, but it doesn't look like this is happening.`nManually copy the endpoint from DISPX to MSOAP and it should run.`n, C:\INTPHARM\Idle.txt
                    sIn =
                    }
            }

;======================CHIL STK READING======================

        chilSTKfile := "C:\INTPHARM\DISPX\chillog_stk_" SCODE ".log"
        Loop, %chilSTKfile%
        {
        FileRead, CstkIn, %A_LoopFileLongPath%
        if RegExMatch(CstkIn, "StatusCode: 500") 
            {
            FileAppend, `n> Error in chillog_stk_%SCODE%.log`nERROR READS >>>`tStatusCode: 500`nSOLUTION >>>`t`tThis can sometimes be fixed by changing the start time of the extraction`, try pushing it out a few hours.`n`t`t`tUnfortunately`, if that doesn't work`, it may be an error on FRED's side.`n`t`t`tSpeak to Brodie about contacting FRED to have them repair this site.`n, C:\INTPHARM\Idle.txt
            sIn = ; Memory cleared
            }
        }
    }

;======================CHIL PAT READING======================

        chilPATfile := "C:\INTPHARM\DISPX\chillog_pat_" SCODE ".log"
        Loop, %chilPATfile%
        {
        FileRead, CpatIn, %A_LoopFileLongPath%
        if RegExMatch(CpatIn, "Cannot authenticate.  Login and/or password not provided.") 
            {
            FileAppend, `n> Error in chillog_pat_%SCODE%.log`nERROR READS >>>`tCannot authenticate. Login and/or password not provided.`nSOLUTION >>>`t`tMissing or incorrect credentials provided in the f_nauth.zip.`n`t`t`tConfirm the correct details are in this file and try again.`n, C:\INTPHARM\Idle.txt
            sIn = ; Memory cleared
            }
        }

;======================ERRORS TEXT READING======================

        errfile := "C:\INTPHARM\DISPX\chillog_stk_" SCODE ".log"
        Loop, %chilSTKfile%
        {
        FileRead, errIn, %A_LoopFileLongPath%
        if RegExMatch(errIn, "Field width or number of decimal places is invalid") 
            {
            FileAppend, `n> Error in errors.txt`nERROR READS >>>`tField width or number of decimal places is invalid.`nSOLUTION >>>`t`tThis can sometimes be fixed by changing the start time of the extraction`, try pushing it out a few hours.`n`t`t`tUnfortunately`, if that doesn't work`, it may be an error on FRED's side.`n`t`t`tSpeak to Brodie about contacting FRED to have them repair this site.`n, C:\INTPHARM\Idle.txt
            sIn = ; Memory cleared
            }
        }
    

;======================CHECK SITECODE FOR SPACES ======================

IfExist, C:\INTPHARM\HSNET\
    {
                HsFile := "C:\INTPHARM\HSNET\sitecode.txt"
        Loop, %HsFile%
        {
        FileRead, HsIn, %A_LoopFileLongPath%
        if RegExMatch(HsIn, " ") 
            {
            FileAppend, `n> HSNET sitecode.txt has spaces in the file. This will cause HSNET to fail any remote updates.`nGo to C:\INTPHARM\HSNET\ and edit the sitecode.txt file to exclude all spaces.`n, C:\INTPHARM\Idle.txt
            sIn =
            }
        }
    }
/*
IfNotExist, %A_Desktop%\Intellipharm Help.url
    {
    FileAppend, `n> Intellipharm Help icon is NOT on the desktop. Make sure you add it.`n, C:\INTPHARM\Idle.txt
    }
*/
FileAppend, `n----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------`n, C:\INTPHARM\Idle.txt    

FileAppend, `nCurrent Versions:, C:\INTPHARM\Idle.txt

        FormatTime, Date,, yyyyMMdd
        FileReadLine, SCODE, C:\INTPHARM\POSX\PRG\sitecode.txt, 1

        SCODE = %SCODE%

    FileReadLine, DISPverRAW, C:\INTPHARM\DISPX\LOGS\DISPX_%Date%.txt, 2
    DISPver := SubStr(DISPverRAW, 43, 17)
    FileAppend, `n%DISPver%, C:\INTPHARM\Idle.txt

    FileReadLine, POSXverRAW, C:\INTPHARM\POSX\REF\%SCODE%_PXLOG_%Date%.txt, 2
    POSXver := SubStr(POSXverRAW, 43, 16)
    FileAppend, `n%POSXver%`n, C:\INTPHARM\Idle.txt

;======================CHECK FOR AV======================

        Process, Exist, ekrn.exe
            {
            If ErrorLevel
            FileAppend, `n>>>>>>>>> ANTIVIRUS = ESET <<<<<<<<<`n, C:\INTPHARM\Idle.txt
            }
        Process, Exist, Navapsvc.exe
            {
            If ErrorLevel
            FileAppend, `n>>>>>>>>> ANTIVIRUS = NORTON <<<<<<<<<`n, C:\INTPHARM\Idle.txt
            }
        Process, Exist, NIS.exe
            {
            If ErrorLevel
            FileAppend, `n>>>>>>>>> ANTIVIRUS = SYMANTEC ENDPOINT <<<<<<<<<`n, C:\INTPHARM\Idle.txt
            }
        Process, Exist, sspaadm.exe
            {
            If ErrorLevel
            FileAppend, `n>>>>>>>>> ANTIVIRUS = SYMANTEC CLOUD <<<<<<<<<`n, C:\INTPHARM\Idle.txt
            }
        Process, Exist, avgui.exe
            {
            If ErrorLevel
            FileAppend, `n>>>>>>>>> ANTIVIRUS = AVG <<<<<<<<<`n, C:\INTPHARM\Idle.txt
            }
        Process, Exist, avguard.exe
            {
            If ErrorLevel
            FileAppend, `n>>>>>>>>> ANTIVIRUS = AVIRA <<<<<<<<<`n, C:\INTPHARM\Idle.txt
            }
        Process, Exist, sophosui.exe
            {
            If ErrorLevel
            FileAppend, `n>>>>>>>>> ANTIVIRUS = SOPHOS <<<<<<<<<`n, C:\INTPHARM\Idle.txt
            }
        Process, Exist, superantispyware.exe
            {
            If ErrorLevel
            FileAppend, `n>>>>>>>>> ANTIVIRUS = SUPER ANTI SPYWARE <<<<<<<<<`n, C:\INTPHARM\Idle.txt
            }
        Process, Exist, wrsa.exe
            {
            If ErrorLevel
            FileAppend, `n>>>>>>>>> ANTIVIRUS = WEBROOT <<<<<<<<<`n, C:\INTPHARM\Idle.txt
            }
        Process, Exist, avastsvc.exe
            {
            If ErrorLevel
            FileAppend, `n>>>>>>>>> ANTIVIRUS = AVAST <<<<<<<<<`n, C:\INTPHARM\Idle.txt
            }
        Process, Exist, msascuil.exe
            {
            If ErrorLevel
            FileAppend, `n>>>>>>>>> ANTIVIRUS = WINDOWS DEFENDER <<<<<<<<<`n, C:\INTPHARM\Idle.txt
            }
        Process, Exist, avp.exe
            {
            If ErrorLevel
            FileAppend, `n>>>>>>>>> ANTIVIRUS = KASPERSKY <<<<<<<<<`n, C:\INTPHARM\Idle.txt
            }
        Process, Exist, OfcService.exe
            {
            If ErrorLevel
            FileAppend, `n>>>>>>>>> ANTIVIRUS = TREND MICRO <<<<<<<<<`n, C:\INTPHARM\Idle.txt
            }
        Process, Exist, PccNTMon.exe
            {
            If ErrorLevel
            FileAppend, `n>>>>>>>>> ANTIVIRUS = TREND MICRO <<<<<<<<<`n, C:\INTPHARM\Idle.txt
            }


;==================== Finished checking for the AV in use            

/* The time check is too comlpicated
elapsed_time = %A_TickCount% ; acquire ticks   
elapsed_time /= 1000 ; compute whole seconds

; get days
f_day = %elapsed_time%
f_day /= 86400.00
Transform, i_day, floor, %f_day%
d_rem = %f_day%
d_rem -= %i_day%

; get hours
f_hour = %d_rem% ; floating remainder
f_hour *= 24
Transform, i_hour, floor, %f_hour%
d_rem = %f_hour%
d_rem -= %i_hour%

; get minutes
f_min = %d_rem%
f_min *= 60
Transform i_min, floor, %f_min%
d_rem = %f_min%
d_rem -= %i_min%

/*
; get seconds
f_sec = %d_rem%
f_sec *= 60
Transform i_sec, floor, %f_sec%
d_rem = %f_sec%
d_rem -= %i_sec%
*/

elapsed_time := (A_TickCount // 1000)
f_hour := mod(elapsed_time, 86400)
f_mins := mod(f_hour, 3600)
uptime := (elapsed_time // 86400) " Days " (f_hour // 3600) " Hrs " (f_mins // 60) " Mins" 

uptime = %uptime% ;%i_day% Days %i_hour% Hrs %i_min% Mins 

FileAppend, `nSystem Uptime - %uptime%`n`n, C:\INTPHARM\Idle.txt    

        Process, Exist, cron.exe
            {
            If ErrorLevel
            FileAppend, >>> CRON is currently running`n, C:\INTPHARM\Idle.txt
            }
        Process, Exist, cron.exe
            {
            If !ErrorLevel
            FileAppend, >>> CRON is NOT currently running`n, C:\INTPHARM\Idle.txt
            }

;==================== HSNET stuff

        Process, Exist, hsnet.exe
            {
            If ErrorLevel
            FileAppend, >>> HSNET is currently running`n, C:\INTPHARM\Idle.txt
            }
        Process, Exist, hsnet.exe
            {
            If !ErrorLevel
            FileAppend, >>> HSNET is NOT currently running`n, C:\INTPHARM\Idle.txt
            }

IfExist, C:\INTPHARM\CRON\cron.tab
    {
    FileReadLine, CronTime, C:\INTPHARM\CRON\cron.tab, 6
    FileAppend, `nCRON Tab:`n%CronTime%`n, C:\INTPHARM\Idle.txt
    }

IniRead, HsnetTimeSet, C:\INTPHARM\HSNET\hsnet.ini, Settings, ScheduleTime

FileAppend, `nHSNET Schedule Time - %HsnetTimeSet%`n, C:\INTPHARM\Idle.txt  

IfExist, C:\INTPHARM\HSNET\LOGS\
    {
    FileReadLine, HsnetTime, C:\INTPHARM\HSNET\LOGS\HSNET_%date%.txt, 1
    FileAppend, `nHSNET Log:`n%HsnetTime%`n, C:\INTPHARM\Idle.txt    
    FileReadLine, HsnetTime2, C:\INTPHARM\HSNET\LOGS\HSNET_%date%.txt, 2
    FileAppend, %HsnetTime2%`n, C:\INTPHARM\Idle.txt    
    }

FileAppend, `n`n############################################################################################, C:\INTPHARM\Idle.txt    
FileAppend, `n##################################### - DOCUMENT END - ########################################, C:\INTPHARM\Idle.txt
FileAppend, `n############################################################################################, C:\INTPHARM\Idle.txt

ExitApp