#SingleInstance, Force
FileDelete, C:\Loyalty\foxrun.pif
FileDelete, C:\Loyalty\foxerun.pif
FileDelete, C:\Loyalty\voucher.txt
FileDelete, C:\Loyalty\livepts.dbf
FileDelete, C:\Loyalty\livepts.cdx
FileDelete, C:\Loyalty\stock*
FileDelete, C:\Loyalty\dept.dbf
FileDelete, C:\Loyalty\dept.cdx
FileDelete, C:\Loyalty\d_2009*
FileDelete, C:\Loyalty\d_2010*
FileDelete, C:\Loyalty\d_2011*
FileDelete, C:\Loyalty\d_2012*
FileDelete, C:\Loyalty\d_2013*
FileDelete, C:\Loyalty\d_2014*
FileDelete, C:\Loyalty\d_2015*